package views.Panels;

import io.socket.client.Socket;
import io.socket.emitter.Emitter;
import views.AjouterCollaborateur;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.Project;
import org.json.JSONObject;

public class PanelAccueil extends javax.swing.JPanel {
    
    Project project;
    
    Socket socket;
    
    JFrame Parent = null;

    public PanelAccueil(Project project, Socket socket) {
        initComponents();
        this.socket = socket;
        this.project = project;
        initComponents2();
        updateInfos();
        
        PanelAccueil self = this;
        
        // Setting up Socket.io
         try {
            socket.on("progress-change-broadcast", new Emitter.Listener() {
                
                @Override
                public void call(Object... args) {
                   System.out.println("Adding user socket event");
                   project.update();
                   System.out.println(project.usersEmails.size());
                   self.updateInfos();
                   self.updateListeCollaborateurs();
                }

            });
            
        } catch (Exception e) {
            System.out.println("error in Main");
            System.out.println(e);
        }
    }

    public void setParent(JFrame Parent) {
        this.Parent = Parent;
    }
    
    public void updateInfos(){
        int progres = project.getProgress();
        int nb_collabs = project.usersEmails.size();
        
        if(progres != -1)
            lblProgres.setText(progres + "%");
        else
            lblProgres.setText("Aucune tâche.");
        lblNbCollab.setText(""+nb_collabs);
//        if(nb_collabs == 1)
//            btnQuitter.setVisible(false);
//        else
//            btnQuitter.setVisible(true);
    }
    
    private void initComponents2() {
        Label1.setText("<html>"+Label1.getText() + "  <b>" + project.getName() + "</b></html>");
        updateListeCollaborateurs();
    }
    
    public void updateListeCollaborateurs()
    {
        lstCollaborateurs.removeAll();
        {
            ArrayList<String> collaborateurs = project.usersEmails;
            DefaultListModel listModel = new DefaultListModel();
            
            for(String nom : collaborateurs)
                listModel.addElement(nom);

            lstCollaborateurs.setModel(listModel);
        }
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAjouterCollaborateur = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Label1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstCollaborateurs = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        lblProgres = new javax.swing.JLabel();
        lblNbCollab = new javax.swing.JLabel();

        setBackground(new java.awt.Color(106, 206, 201));

        btnAjouterCollaborateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BoutonAjouterCollaborateur.png"))); // NOI18N
        btnAjouterCollaborateur.setBorderPainted(false);
        btnAjouterCollaborateur.setContentAreaFilled(false);
        btnAjouterCollaborateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterCollaborateurActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lao UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Progrès Global ");

        jLabel1.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Liste des collaborateurs");

        Label1.setFont(new java.awt.Font("Lao UI", 1, 18)); // NOI18N
        Label1.setForeground(new java.awt.Color(255, 255, 255));
        Label1.setText("Tableau de bord du projet : ");

        lstCollaborateurs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        lstCollaborateurs.setFont(new java.awt.Font("Lao UI", 0, 18)); // NOI18N
        lstCollaborateurs.setForeground(new java.awt.Color(0, 51, 51));
        lstCollaborateurs.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstCollaborateurs);

        jLabel3.setFont(new java.awt.Font("Lao UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Nombre de collaborateurs ");

        lblProgres.setFont(new java.awt.Font("Lao UI", 0, 52)); // NOI18N
        lblProgres.setForeground(new java.awt.Color(255, 255, 255));
        lblProgres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProgres.setText("100%");

        lblNbCollab.setFont(new java.awt.Font("Lao UI", 0, 48)); // NOI18N
        lblNbCollab.setForeground(new java.awt.Color(255, 255, 255));
        lblNbCollab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNbCollab.setText("12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblNbCollab, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProgres, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAjouterCollaborateur)
                        .addGap(24, 24, 24))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProgres)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAjouterCollaborateur, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNbCollab, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterCollaborateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterCollaborateurActionPerformed
        AjouterCollaborateur FrAjouterCollaborateur = new AjouterCollaborateur(socket);
        FrAjouterCollaborateur.setParent(this);
        FrAjouterCollaborateur.setProjet(project);
        FrAjouterCollaborateur.setVisible(true);
        updateInfos();
    }//GEN-LAST:event_btnAjouterCollaborateurActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label1;
    private javax.swing.JButton btnAjouterCollaborateur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNbCollab;
    private javax.swing.JLabel lblProgres;
    private javax.swing.JList lstCollaborateurs;
    // End of variables declaration//GEN-END:variables

}
