/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.JFrame;

import models.User;

public class Accueil extends javax.swing.JFrame {
    JFrame Parent;
    User user;
    
    public Accueil() {
        pack();
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Accueil(User user) {
        this.user  = user;
        pack();
        initComponents();
        setLocationRelativeTo(null);
        System.out.println("User is:" +  user.getEmail());
    }

    public void setParent(JFrame Parent) {
        this.Parent = Parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRejoindreProjet = new javax.swing.JButton();
        btnCreerProjet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(106, 206, 201));
        jPanel1.setDoubleBuffered(false);
        jPanel1.setEnabled(false);
        jPanel1.setFocusable(false);

        btnRejoindreProjet.setBackground(new java.awt.Color(255, 255, 255));
        btnRejoindreProjet.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        btnRejoindreProjet.setForeground(new java.awt.Color(0, 102, 102));
        btnRejoindreProjet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BoutonMesProjets.png"))); // NOI18N
        btnRejoindreProjet.setBorder(null);
        btnRejoindreProjet.setBorderPainted(false);
        btnRejoindreProjet.setContentAreaFilled(false);
        btnRejoindreProjet.setFocusPainted(false);
        btnRejoindreProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejoindreProjetActionPerformed(evt);
            }
        });

        btnCreerProjet.setBackground(new java.awt.Color(255, 255, 255));
        btnCreerProjet.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        btnCreerProjet.setForeground(new java.awt.Color(0, 102, 102));
        btnCreerProjet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/BoutonCreerProjet.png"))); // NOI18N
        btnCreerProjet.setBorder(null);
        btnCreerProjet.setBorderPainted(false);
        btnCreerProjet.setContentAreaFilled(false);
        btnCreerProjet.setFocusPainted(false);
        btnCreerProjet.setRequestFocusEnabled(false);
        btnCreerProjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreerProjetActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        jLabel1.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRejoindreProjet)
                            .addComponent(btnCreerProjet))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(btnCreerProjet, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnRejoindreProjet, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRejoindreProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejoindreProjetActionPerformed
        Selection FrSelection = new Selection(user);
        FrSelection.setParent(this);
        FrSelection.setVisible(true);
//        setVisible(false);
    }//GEN-LAST:event_btnRejoindreProjetActionPerformed

    private void btnCreerProjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreerProjetActionPerformed
        CreationProjet FrCreationProjet = new CreationProjet(user);
        FrCreationProjet.setParent(this);
        FrCreationProjet.setVisible(true);
    }//GEN-LAST:event_btnCreerProjetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil(new User("edmeral.aissam@gmail.com", "123456")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreerProjet;
    private javax.swing.JButton btnRejoindreProjet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
